wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.9
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1694665936.353925
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.10.8
      5: 0.15.9
      8:
      - 1
      - 5
